// MOCK_DATA_REMOVE_BEFORE_PRODUCTION: preview-only fixtures; never use as production API data.
import type {
  BannerItem,
  CartItem,
  Category,
  CustomerUser,
  EventItem,
  Product,
  ProjectItem,
  StoreSettings,
} from '@/types';
import type { BackendUser } from '@/types/auth';
import type { CustomDesignRequest } from '@/types/customDesign';
import type { BackendOffer } from '@/types/offer';
import type { BackendOrder } from '@/types/order';

const diningTableImage = 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=85';
const loungeImage = 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85';
const chairImage = 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1400&q=85';
const cabinetImage = 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1400&q=85';

export const previewProducts: Product[] = [
  {
    id: '701',
    slug: 'modern-dining-table',
    name: 'طاولة سفرة مودرن',
    categoryId: '801',
    subcategoryIds: [],
    description: 'طاولة سفرة بتصميم عصري يمكن تنفيذها بالمقاس واللون المناسب لمساحتك.',
    price: 0,
    images: [diningTableImage, loungeImage],
    dimensions: 'تُنفذ حسب المقاس المطلوب',
    deliveryDays: null,
    material: 'خشب طبيعي، تشطيب حسب الاختيار',
    finishes: ['MATTE', 'GLOSSY'],
    colors: [
      { id: '7011', name: 'بيج', hex: '#D8C6AA' },
      { id: '7012', name: 'خشبي طبيعي', hex: '#A47A53' },
      { id: '7013', name: 'أوف وايت', hex: '#F1EDE4' },
      { id: '7014', name: 'بني داكن', hex: '#49382D' },
    ],
    sizes: [],
    faq: [],
    leadTime: 'حسب الطلب',
    shippingTime: 'يؤكد بعد مراجعة الطلب',
    isFeatured: true,
    isPublished: true,
    inStock: true,
    allowsCustomization: true,
    createdAt: '2026-01-12T10:00:00Z',
  },
  {
    id: '702',
    slug: 'modern-tv-unit',
    name: 'وحدة تلفزيون مودرن',
    categoryId: '801',
    subcategoryIds: [],
    description: 'وحدة تلفزيون بخطوط هادئة ومساحات تخزين، تُنفذ بما يناسب أبعاد الحائط.',
    price: 0,
    images: [cabinetImage],
    dimensions: 'تُنفذ حسب المقاس المطلوب',
    deliveryDays: null,
    material: 'خشب معالج، تشطيب حسب الاختيار',
    finishes: ['MATTE'],
    colors: [
      { id: '7021', name: 'خشبي طبيعي', hex: '#A47A53' },
      { id: '7022', name: 'أوف وايت', hex: '#F1EDE4' },
    ],
    sizes: [],
    faq: [],
    leadTime: 'حسب الطلب',
    isFeatured: true,
    isPublished: true,
    inStock: true,
    allowsCustomization: true,
    createdAt: '2026-02-08T10:00:00Z',
  },
  {
    id: '703',
    slug: 'modern-buffet',
    name: 'بوفيه مودرن',
    categoryId: '801',
    subcategoryIds: [],
    description: 'بوفيه عملي بتفاصيل بسيطة ومساحة تخزين واسعة، يُصمم حسب احتياجك.',
    price: 0,
    images: [cabinetImage, diningTableImage],
    dimensions: 'تُنفذ حسب المقاس المطلوب',
    deliveryDays: null,
    material: 'خشب طبيعي، تشطيب حسب الاختيار',
    finishes: ['MATTE', 'GLOSSY'],
    colors: [
      { id: '7031', name: 'بيج', hex: '#D8C6AA' },
      { id: '7032', name: 'بني داكن', hex: '#49382D' },
    ],
    sizes: [],
    faq: [],
    leadTime: 'حسب الطلب',
    isFeatured: false,
    isPublished: true,
    inStock: true,
    allowsCustomization: true,
    createdAt: '2026-02-22T10:00:00Z',
  },
  {
    id: '704',
    slug: 'imported-lounge-chair',
    name: 'كرسي Lounge',
    categoryId: '802',
    subcategoryIds: [],
    description: 'كرسي استرخاء بتصميم مريح وتفاصيل جاهزة للاختيار.',
    price: 8500,
    images: [loungeImage],
    dimensions: 'عرض ٨٠ × عمق ٨٢ × ارتفاع ٧٦ سم',
    deliveryDays: 14,
    material: 'قماش، خشب طبيعي',
    finishes: ['MATTE'],
    colors: [
      { id: '7041', name: 'بيج', hex: '#D8C6AA' },
      { id: '7042', name: 'رمادي', hex: '#898A88' },
      { id: '7043', name: 'بني داكن', hex: '#49382D' },
    ],
    sizes: [],
    faq: [],
    leadTime: '١٤ يومًا',
    shippingTime: 'يؤكد بعد مراجعة الطلب',
    isFeatured: true,
    isPublished: true,
    inStock: true,
    allowsCustomization: false,
    createdAt: '2026-03-10T10:00:00Z',
  },
  {
    id: '705',
    slug: 'imported-side-table',
    name: 'طاولة جانبية',
    categoryId: '802',
    subcategoryIds: [],
    description: 'طاولة جانبية بخامة طبيعية وحجم مناسب بجوار الأريكة أو السرير.',
    price: 3200,
    images: [diningTableImage],
    dimensions: 'قطر ٤٥ × ارتفاع ٥٢ سم',
    deliveryDays: 10,
    material: 'خشب طبيعي',
    finishes: ['MATTE'],
    colors: [{ id: '7051', name: 'خشبي طبيعي', hex: '#A47A53' }],
    sizes: [],
    faq: [],
    leadTime: '١٠ أيام',
    isFeatured: true,
    isPublished: true,
    inStock: true,
    allowsCustomization: false,
    createdAt: '2026-03-18T10:00:00Z',
  },
  {
    id: '706',
    slug: 'imported-accent-chair',
    name: 'كرسي Accent',
    categoryId: '802',
    subcategoryIds: [],
    description: 'كرسي بتصميم لافت ولمسة لونية تضيف شخصية للمكان.',
    price: 6900,
    images: [chairImage],
    dimensions: 'عرض ٧٢ × عمق ٧٦ × ارتفاع ٨٠ سم',
    deliveryDays: 12,
    material: 'قماش، معدن مطلي',
    finishes: ['MATTE'],
    colors: [
      { id: '7061', name: 'بيج', hex: '#D8C6AA' },
      { id: '7062', name: 'أخضر زيتوني', hex: '#74745C' },
    ],
    sizes: [],
    faq: [],
    leadTime: '١٢ يومًا',
    isFeatured: false,
    isPublished: true,
    inStock: true,
    allowsCustomization: false,
    createdAt: '2026-04-02T10:00:00Z',
  },
  {
    id: '707',
    slug: 'imported-storage-unit',
    name: 'وحدة تخزين',
    categoryId: '802',
    subcategoryIds: [],
    description: 'وحدة تخزين متعددة الاستخدامات بواجهات بسيطة وتفاصيل عملية.',
    price: 9500,
    images: [cabinetImage],
    dimensions: 'عرض ١٢٠ × عمق ٤٠ × ارتفاع ٩٠ سم',
    deliveryDays: 16,
    material: 'خشب هندسي، قشرة طبيعية',
    finishes: ['MATTE'],
    colors: [
      { id: '7071', name: 'خشبي طبيعي', hex: '#A47A53' },
      { id: '7072', name: 'أوف وايت', hex: '#F1EDE4' },
    ],
    sizes: [],
    faq: [],
    leadTime: '١٦ يومًا',
    isFeatured: true,
    isPublished: true,
    inStock: true,
    allowsCustomization: false,
    createdAt: '2026-04-12T10:00:00Z',
  },
];

export const previewCategories: Category[] = [
  {
    id: '801',
    name: 'تصنيع حسب الطلب',
    slug: 'made-to-order',
    description: 'قطع تُنفذ حسب المقاس واللون والخامة التي تختارها.',
    image: diningTableImage,
    isFeatured: true,
    displayOrder: 1,
    isVisible: true,
  },
  {
    id: '802',
    name: 'مستورد',
    slug: 'imported',
    description: 'تصميمات جاهزة بمواصفات وألوان محددة.',
    image: loungeImage,
    isFeatured: true,
    displayOrder: 2,
    isVisible: true,
  },
];

export const previewProjects: ProjectItem[] = [
  {
    id: '9101',
    title: 'مشروع شقة التجمع',
    subtitle: 'مساحة معيشة عصرية',
    description: 'تنسيق غرفة المعيشة ومنطقة الطعام بقطع بألوان دافئة وخامات طبيعية.',
    location: 'القاهرة الجديدة، القاهرة',
    coverImage: loungeImage,
    gallery: [loungeImage, diningTableImage],
    productsUsed: ['طاولة سفرة مودرن', 'كرسي Lounge'],
    featuredPieces: ['طاولة سفرة مودرن', 'كرسي Lounge'],
    year: '٢٠٢٦',
    customerName: 'مشروع تجريبي',
    productId: '701',
  },
  {
    id: '9102',
    title: 'مشروع فيلا الشيخ زايد',
    subtitle: 'تصميم معاصر',
    description: 'اختيارات أثاث وديكور هادئة لمساحة مفتوحة بإضاءة طبيعية.',
    location: 'الشيخ زايد، الجيزة',
    coverImage: cabinetImage,
    gallery: [cabinetImage, chairImage],
    productsUsed: ['وحدة تلفزيون مودرن', 'كرسي Accent'],
    featuredPieces: ['وحدة تلفزيون مودرن', 'كرسي Accent'],
    year: '٢٠٢٦',
    customerName: 'مشروع تجريبي',
  },
  {
    id: '9103',
    title: 'مشروع شقة مصر الجديدة',
    subtitle: 'دفء وبساطة',
    description: 'توازن بين الألوان الفاتحة والتخزين العملي في مساحة منزلية.',
    location: 'مصر الجديدة، القاهرة',
    coverImage: diningTableImage,
    gallery: [diningTableImage, chairImage],
    productsUsed: ['بوفيه مودرن', 'طاولة جانبية'],
    featuredPieces: ['بوفيه مودرن', 'طاولة جانبية'],
    year: '٢٠٢٥',
    customerName: 'مشروع تجريبي',
  },
];

export const previewEvents: EventItem[] = [
  {
    id: '9201',
    title: 'معرض مودرن هوم للأثاث',
    subtitle: 'مجموعة مختارة',
    description: 'تعرف على قطع الأثاث والتصميمات الجديدة من مودرن هوم.',
    location: 'القاهرة الجديدة',
    city: 'القاهرة',
    date: '2026-11-15',
    time: '12:00',
    coverImage: loungeImage,
    status: 'upcoming',
    isUpcoming: true,
  },
  {
    id: '9202',
    title: 'فعالية التصميم الداخلي',
    subtitle: 'جلسة حوارية',
    description: 'لقاء حول اختيار الأثاث وتنسيق المساحات المنزلية.',
    location: 'الشيخ زايد',
    city: 'الجيزة',
    date: '2026-12-02',
    coverImage: chairImage,
    status: 'upcoming',
    isUpcoming: true,
  },
];

export const previewSettings: StoreSettings = {
  brandName: 'Modern Home',
  tagline: 'للأثاث والديكور العصري',
  subTagline: 'مودرن هوم',
  depositPercentage: 50,
  defaultLeadTime: 'حسب الطلب',
  defaultShippingTime: 'يتم تأكيد تفاصيل التوصيل بعد مراجعة الطلب',
  contact: {
    phone: '+201039323247',
    whatsapp: '+201039323247',
    email: 'preview@example.invalid',
    atelierAddress: 'القاهرة، مصر',
    mapUrl: 'https://maps.google.com/?q=Cairo,Egypt',
    instagramHandles: ['@modern.home.preview'],
    hours: 'الزيارة بموعد مسبق',
  },
  paymentMethods: {
    instapay: {
      active: false,
      address: 'preview@instapay.invalid',
      accountName: 'حساب تجريبي',
      instructions: 'بيانات تجريبية للمعاينة فقط.',
    },
    mobileWallet: {
      active: false,
      number: '01000000000',
      provider: 'محفظة تجريبية',
      instructions: 'بيانات تجريبية للمعاينة فقط.',
    },
    vodafoneCash: {
      active: false,
      number: '01000000000',
      instructions: 'بيانات تجريبية للمعاينة فقط.',
    },
    bankTransfer: {
      active: false,
      bankName: 'بيانات تجريبية',
      accountNumber: '000000000000',
      iban: 'EG0000000000000000000000000',
      swift: 'PREVEGCA',
      accountHolder: 'حساب تجريبي',
      accountName: 'حساب تجريبي',
      instructions: 'بيانات تجريبية للمعاينة فقط.',
    },
  },
  homepage: {
    heroHeading: 'بيتك يبدأ من اختيارك',
    heroSubheading: 'أثاث عصري بتصميمات مختارة، وحلول مخصصة تناسب مساحتك وذوقك.',
    heroCtaText: 'تصفح المنتجات',
    heroImage: '/images/hero_villa_clean.jpg',
    storyQuote: 'أثاث يكمّل روح المكان',
    storySubtext: 'تصميمات مناسبة لمساحتك.',
  },
  policies: {
    shipping: '',
    returns: '',
    privacy: '',
    terms: '',
    faq: [],
  },
};

export const previewBanners: BannerItem[] = [
  {
    id: '9301',
    type: 'new_product',
    categoryLabel: 'وصل حديثًا',
    badgeText: 'مجموعة جديدة',
    title: 'تفاصيل جديدة لمساحتك',
    subtitle: 'اكتشف القطع المختارة من مودرن هوم.',
    image: loungeImage,
    ctaText: 'اكتشف المجموعة',
    actionType: 'navigate',
    targetView: 'shop',
    isActive: true,
    displayOrder: 1,
  },
  {
    id: '9302',
    type: 'special_offer',
    categoryLabel: 'عرض خاص',
    badgeText: 'لفترة محدودة',
    title: 'عرض على مجموعة غرفة المعيشة',
    subtitle: 'تفاصيل العرض تجريبية للمعاينة.',
    image: chairImage,
    ctaText: 'اكتشف العرض',
    actionType: 'copy_code',
    targetView: 'shop',
    promoCode: 'MODERNHOME',
    isActive: true,
    displayOrder: 2,
  },
];

export const previewOffers: BackendOffer[] = [
  {
    id: 9401,
    name: 'خصم خاص على كرسي Lounge',
    offer_type: 'PERCENTAGE',
    percentage: '10',
    bundle_price: null,
    products: [{ id: 94011, product_id: 704, product_name: 'كرسي Lounge', product_price: '8500.00', quantity: 1 }],
    original_price: '8500.00',
    discount_amount: '850.00',
    offer_price: '7650.00',
    starts_at: '2026-09-01T00:00:00Z',
    ends_at: '2026-11-30T23:59:59Z',
    is_active: true,
    created_at: '2026-08-20T10:00:00Z',
    updated_at: '2026-08-20T10:00:00Z',
  },
];

export const previewCustomDesignRequests: CustomDesignRequest[] = [
  {
    id: 9501,
    user: 501,
    title: 'طاولة سفرة حسب المقاس',
    request_type: 'CLIENT',
    dimensions: { width_cm: 220, height_cm: 76, depth_cm: 95 },
    quantity: 1,
    description: 'طاولة سفرة لستة أشخاص بلون خشبي طبيعي.',
    contact_phone: '01000000000',
    company_name: '',
    project_location: 'القاهرة الجديدة',
    target_delivery_date: '2026-12-15',
    images: [
      {
        id: 95011,
        request: 9501,
        image: diningTableImage,
        public_id: 'preview/modern-home/dining-table',
        sort_order: 1,
        created_at: '2026-09-18T12:00:00Z',
      },
    ],
    created_at: '2026-09-18T12:00:00Z',
    updated_at: '2026-09-18T12:00:00Z',
  },
];

export const previewCart: CartItem[] = [
  {
    id: 'preview-cart-1',
    productId: '704',
    productName: 'كرسي Lounge',
    productImage: loungeImage,
    unitPrice: 8500,
    selectedFinish: 'MATTE',
    selectedColor: { id: '7041', name: 'بيج', hex: '#D8C6AA' },
    quantity: 1,
  },
];

export const previewUser: CustomerUser = {
  id: 'preview-user-501',
  fullName: 'عميل تجريبي',
  email: 'customer@example.invalid',
  phone: '01000000000',
  role: 'CUSTOMER',
  savedAddresses: [
    {
      id: 'preview-address-1',
      label: 'المنزل',
      governorate: 'القاهرة',
      city: 'القاهرة الجديدة',
      street: 'عنوان تجريبي للمعاينة',
      building: '١٢',
      apartment: '٤',
      is_default: true,
    },
  ],
};

export const previewBackendUser: BackendUser = {
  id: 501,
  first_name: 'عميل',
  last_name: 'تجريبي',
  email: 'customer@example.invalid',
  phone: '01000000000',
  role: 'CUSTOMER',
  is_active: true,
  created_at: '2026-09-01T10:00:00Z',
};

export const previewOrder: BackendOrder = {
  id: 9601,
  order_number: 'MH-PREVIEW-9601',
  user: {
    id: 501,
    first_name: 'عميل',
    last_name: 'تجريبي',
    email: 'customer@example.invalid',
    phone: '01000000000',
  },
  address_id: 9701,
  shipping_address: {
    title: 'المنزل',
    country: 'مصر',
    city: 'القاهرة الجديدة',
    street: 'عنوان تجريبي للمعاينة',
    building_number: '١٢',
    apartment_number: '٤',
  },
  status: 'NOT_CONFIRMED',
  customer_notes: 'هذا الطلب تجريبي للمعاينة فقط.',
  total_price: '8500.00',
  deposit_percentage: '50.00',
  deposit_amount: '4250.00',
  items: [
    {
      id: 96011,
      product_id: 704,
      product_name: 'كرسي Lounge',
      product_price: '8500.00',
      color_name: 'بيج',
      color_hex_code: '#D8C6AA',
      selected_finish: 'MATTE',
      quantity: 1,
      subtotal: '8500.00',
    },
  ],
  created_at: '2026-09-20T10:00:00Z',
  updated_at: '2026-09-20T10:00:00Z',
};
